### ISSUE TITLE
clhash is 3x slower than std::hash in Mac OS and 2x slower than std::hash in Linux

### ISSUE THREAD

**Issue by hungptit** [lemire/clhash#6]
Hi Daniel,

I write a simple benchmark using https://github.com/google/benchmark and my benchmark results show that clhash is 3 times slower than std::hash in my MacBook Pro and 2 times slower than std::hash in Centos 6  with Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz. You can find my benchmark and CMakeLists.txt files from my GitHub folder https://github.com/hungptit/clhash/tree/convert.to.header.only.library/benchmark.

Do you have any suggestion? 

Regards,
Hung

Benchmark results obtained in my MacBook Pro

```
./basic_benchmark
2018-10-25 22:57:00
Running ./basic_benchmark
Run on (8 X 2200 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 6291K (x1)
-------------------------------------------------------
Benchmark                Time           CPU Iterations
-------------------------------------------------------
std_hash_string          5 ns          5 ns  138334453
clhash_string           17 ns         17 ns   36479233
```

Benchmark results obtained in Centos with gcc-5.5
```
2018-10-25 23:08:44
Running ./basic_benchmark
Run on (88 X 2199.89 MHz CPU s)
CPU Caches:
  L1 Data 32K (x44)
  L1 Instruction 32K (x44)
  L2 Unified 256K (x44)
  L3 Unified 56320K (x2)
-------------------------------------------------------
Benchmark                Time           CPU Iterations
-------------------------------------------------------
std_hash_string         12 ns         12 ns   60746327
clhash_string           23 ns         23 ns   30505677
```

**Comment by fsaintjacques** [comment]
How did you invoke cmake? What are the compile flags?

**Comment by fsaintjacques** [comment]
Try increasing the size of the string, this is where it'll shine.

**Comment by lemire** [comment]
@fsaintjacques is correct.

Optimizing for speed with tiny strings is a vastly different problem than for long strings. Of course, you can optimize for both cases with some kind of branching and so forth... but clhash has not been optimized in this manner. I will add a paragraph to the README to make sure it is clear.

I have issued a PR on your fork, consider merging it...
https://github.com/hungptit/clhash/pull/2

Report back if you can't get good speed with sensibly long strings... 

Of course, a PR which would provide fast speeds on tiny strings would be welcome. But it is not a bug that we can't match std::hash on tiny strings... it was not a design objective.

**Comment by lemire** [comment]
I have added a remark in the README as part of this commit:

https://github.com/lemire/clhash/commit/5511441cf3ae2c4f064e2e2950e754eb2033b56c

**Comment by fsaintjacques** [comment]
As a future reference, you might make a graph with regards of input size :)

**Comment by lemire** [comment]
Indeed. 

A really good benchmark would actually include a realistic mix of string inputs, with various (unpredictable) lengths.

**Comment by hungptit** [comment]
I have created a simple benchmark using randomly generated strings to automatically detect when clhash is faster than std::hash. The benchmark results obtained in my MacBook Pro show that clhash is faster than std::hash when the size of the string is greater than or equal to 192 bytes. You can find my benchmark code, automated scripts, and a sample PDF picture in my github folder https://github.com/hungptit/clhash/blob/convert.to.header.only.library/benchmark/. Regards. Hung.

**Comment by lemire** [comment]
This sounds credible, yes.
